.PHONY: main t

main:
	python3 src/main.py

t:
	pytest tests/test_simple_problem.py -v 
	pytest tests/test_bfs.py -v 
	pytest tests/test_dfs.py -v 
	pytest tests/test_astar.py -v 
	#pytest tests/test_corner_search.py -v 
	#pytest tests/test_gem_search.py -v 
	
